version: '3'

env:
  IMAGE_NAME: '{{ .IMAGE_NAME | default "<YOUR-USERNAME>/<IMAGE-NAME>:<IMAGE-TAG>" }}'

build:
  desc: "Build a project using Golang"
  cmds:
    - go build -o ./out/app ./cmd/proxy

dockerBuild:
  desc: "Build a Docker image using the specified Dockerfile and tag it with the provided image name."
  cmds:
    - docker build -t {{ .IMAGE_NAME }} -f .\build\Dockerfile .

dockerPush:
  desc: "Push the Docker image to the remote registry with the specified image name."
  cmds:
    - docker push {{ .IMAGE_NAME }}